--CREACIÓN DE TABLA PARA ALMACENAR LOS FACTURADORES [FACTURATECH, FENALCO]
CREATE TABLE Facturador
(
	IdFacturador INT UNIQUE IDENTITY NOT NULL,
	Facturador VARCHAR(70) NOT NULL
)

--SE REALIZA INSERCIÓN DE LOS FACTURADORES
INSERT INTO Facturador VALUES ('Facturatech')
INSERT INTO Facturador VALUES ('Fenalco')

--SE AGREGA COLUMNA EN LA TABLA CREDENCIALESWSDLFACTURATECH
ALTER TABLE dbo.CredencialesWSDLFacturaTech
ADD IdFacturador INT

--SE AGREGA COLUMNA EN LA TABLA EMPRESAV PARA TRABAJAR CON EL IDNUMERACION QUE REGISTRA FENALCO, EN PLATAFORMA FENALCO.
--SE VERIFICA EN LA RESOLUCIÓN VIGENTE REGISTRADA EN FENALCO
ALTER TABLE dbo.EmpresaV 
ADD IdNumeracion INT NULL